INTERFACE zif_otel_otlp_common PUBLIC.
* Generated by AI - do not maintain manually
* Based on opentelemetry/proto/common/v1/common.proto

  TYPES:
    "! AnyValue represents any type of attribute value
    BEGIN OF any_value,
      string_value TYPE string,
      bool_value   TYPE xsdboolean,
      int_value    TYPE string, "int64 as string
      double_value TYPE f,
      array_value  TYPE REF TO data, "array_value type
      kvlist_value TYPE REF TO data, "key_value_list type
      bytes_value  TYPE string,
    END OF any_value,

    "! Array of any_value elements
    BEGIN OF array_value,
      values TYPE STANDARD TABLE OF any_value WITH EMPTY KEY,
    END OF array_value,

    "! Single key-value pair
    BEGIN OF key_value,
      key   TYPE string,
      value TYPE any_value,
    END OF key_value,

    "! List of key-value pairs
    BEGIN OF key_value_list,
      values TYPE STANDARD TABLE OF key_value WITH EMPTY KEY,
    END OF key_value_list,

    "! Instrumentation scope information
    BEGIN OF instrumentation_scope,
      name                    TYPE string,
      version                 TYPE string,
      attributes             TYPE STANDARD TABLE OF key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
    END OF instrumentation_scope.

ENDINTERFACE.
