"! <p class="shorttext">OTLP Resource Interface</p>
"! Generated by AI - do not maintain manually
INTERFACE zif_otel_otlp_resource PUBLIC.

  TYPES:
    "! Resource information
    BEGIN OF resource,
      attributes              TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
    END OF resource.

ENDINTERFACE.
