"! <p class="shorttext">OTLP Common Interface</p>
"! Generated by AI - do not maintain manually
INTERFACE zif_otel_otlp_common PUBLIC.

  TYPES:
    "! Array of any values
    BEGIN OF array_value,
      values TYPE STANDARD TABLE OF REF TO data WITH EMPTY KEY, "Will be any_value after declaration
    END OF array_value,

    "! Key-value list
    BEGIN OF key_value_list,
      values TYPE STANDARD TABLE OF REF TO data WITH EMPTY KEY, "Will be key_value after declaration
    END OF key_value_list,

    "! Any value type
    BEGIN OF any_value,
      string_value TYPE string,
      bool_value   TYPE xsdboolean,
      int_value    TYPE i8,
      double_value TYPE f,
      array_value  TYPE array_value,
      kvlist_value TYPE key_value_list,
      bytes_value  TYPE string,
    END OF any_value,

    "! Key-value pair
    BEGIN OF key_value,
      key   TYPE string,
      value TYPE any_value,
    END OF key_value,

    "! Instrumentation scope
    BEGIN OF instrumentation_scope,
      name                    TYPE string,
      version                 TYPE string,
      attributes             TYPE STANDARD TABLE OF key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
    END OF instrumentation_scope.

ENDINTERFACE.
