INTERFACE zif_otel_otlp_resource PUBLIC.
* This file is generated by AI. Do not modify manually.

  TYPES:
    "! Resource information
    BEGIN OF resource,
      attributes              TYPE zif_otel_otlp_common=>key_value_list_values,
      dropped_attributes_count TYPE i,
    END OF resource.

ENDINTERFACE.
