INTERFACE zif_otel_otlp_common PUBLIC.
* This file is generated by AI. Do not modify manually.

  TYPES:
    "! AnyValue primitive type
    BEGIN OF any_value,
      string_value TYPE string,
      bool_value   TYPE abap_bool,
      int_value    TYPE int8,
      double_value TYPE f,
      array_value  TYPE REF TO data, "! Will contain array_value type
      kvlist_value TYPE REF TO data, "! Will contain key_value_list type
      bytes_value  TYPE xstring,
    END OF any_value,

    "! Array of any values
    BEGIN OF array_value,
      values TYPE STANDARD TABLE OF any_value WITH EMPTY KEY,
    END OF array_value,

    "! Key-value pair
    BEGIN OF key_value,
      key   TYPE string,
      value TYPE any_value,
    END OF key_value,

    "! Table of key-value pairs
    key_value_list_values TYPE STANDARD TABLE OF key_value WITH EMPTY KEY,

    "! Key-value list wrapper
    BEGIN OF key_value_list,
      values TYPE key_value_list_values,
    END OF key_value_list,

    "! Instrumentation scope
    BEGIN OF instrumentation_scope,
      name                     TYPE string,
      version                  TYPE string,
      attributes              TYPE key_value_list_values,
      dropped_attributes_count TYPE i,
    END OF instrumentation_scope.

ENDINTERFACE.
