INTERFACE zif_otel_otlp_metrics PUBLIC.
* This file is generated by AI. Do not modify manually.

  TYPES:
    "! Aggregation temporality type
    aggregation_temporality_type TYPE i,

    "! Data point flags type
    data_point_flags_type TYPE i.

  CONSTANTS:
    BEGIN OF aggregation_temporality,
      unspecified TYPE aggregation_temporality_type VALUE 0,
      delta       TYPE aggregation_temporality_type VALUE 1,
      cumulative  TYPE aggregation_temporality_type VALUE 2,
    END OF aggregation_temporality,

    BEGIN OF data_point_flags,
      no_recorded_value_mask TYPE data_point_flags_type VALUE 1,
    END OF data_point_flags.

  TYPES:
    "! Exemplar
    BEGIN OF exemplar,
      filtered_attributes
