"! <p class="shorttext synchronized">OpenTelemetry OTLP Metrics Interface</p>
"! This file is generated by AI. DO NOT MODIFY MANUALLY.
INTERFACE zif_otel_otlp_metrics PUBLIC.

  TYPES:
    aggregation_temporality_type TYPE i.

  CONSTANTS:
    BEGIN OF aggregation_temporality,
      unspecified TYPE aggregation_temporality_type VALUE 0,
      delta       TYPE aggregation_temporality_type VALUE 1,
      cumulative  TYPE aggregation_temporality_type VALUE 2,
    END OF aggregation_temporality.

  TYPES:
    "! Exemplar
    BEGIN OF exemplar,
      filtered_attributes      TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      time_unix_nano          TYPE string, "UNIX timestamp
      as_double              TYPE f,
      as_int                 TYPE i,
      span_id                TYPE string,
      trace_id               TYPE string,
    END OF exemplar,

    "! Number data point
    BEGIN OF number_data_point,
      attributes              TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      start_time_unix_nano   TYPE string, "UNIX timestamp
      time_unix_nano         TYPE string, "UNIX timestamp
      as_double             TYPE f,
      as_int                TYPE i,
      exemplars              TYPE STANDARD TABLE OF exemplar WITH EMPTY KEY,
      flags                  TYPE i,
    END OF number_data
