"! <p class="shorttext synchronized">OpenTelemetry OTLP Resource Interface</p>
"! This file is generated by AI. DO NOT MODIFY MANUALLY.
INTERFACE zif_otel_otlp_resource PUBLIC.

  TYPES:
    "! Resource information
    BEGIN OF resource,
      attributes              TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
    END OF resource.

ENDINTERFACE.
