"! <p class="shorttext synchronized">OpenTelemetry OTLP Trace Interface</p>
"! This file is generated by AI. DO NOT MODIFY MANUALLY.
INTERFACE zif_otel_otlp_trace PUBLIC.

  TYPES:
    "! Status code type
    status_code_type TYPE i,

    "! Span kind type  
    span_kind_type TYPE i.

  CONSTANTS:
    BEGIN OF status_code,
      unset TYPE status_code_type VALUE 0,
      ok    TYPE status_code_type VALUE 1,
      error TYPE status_code_type VALUE 2,
    END OF status_code,

    BEGIN OF span_kind,
      unspecified TYPE span_kind_type VALUE 0,
      internal    TYPE span_kind_type VALUE 1,
      server      TYPE span_kind_type VALUE 2,
      client      TYPE span_kind_type VALUE 3,
      producer    TYPE span_kind_type VALUE 4,
      consumer    TYPE span_kind_type VALUE 5,
    END OF span_kind.

  TYPES:
    "! Status of span
    BEGIN OF status,
      message TYPE string,
      code    TYPE status_code_type,
    END OF status,

    "! Event in a span
    BEGIN OF event,
      time_unix_nano          TYPE string, "UNIX timestamp
      name                    TYPE string,
      attributes              TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
    END OF event,

    "! Link to another span
    BEGIN OF link,
      trace_id                TYPE string,
      span_id                 TYPE string,
      trace_state            TYPE string,
      attributes              TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
      flags                   TYPE i,
    END OF link,

    "! Span represents a single operation
    BEGIN OF span,
      trace_id                TYPE string,
      span_id                 TYPE string,
      trace_state            TYPE string,
      parent_span_id         TYPE string,
      name                    TYPE string,
      kind                    TYPE span_kind_type,
      start_time_unix_nano   TYPE string, "UNIX timestamp
      end_time_unix_nano     TYPE string, "UNIX timestamp
      attributes              TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
      events                  TYPE STANDARD TABLE OF event WITH EMPTY KEY,
      dropped_events_count    TYPE i,
      links                   TYPE STANDARD TABLE OF link WITH EMPTY KEY,
      dropped_links_count     TYPE i,
      status                  TYPE status,
      flags                   TYPE i,
    END OF span,

    "! Collection of spans from an instrumentation scope
    BEGIN OF scope_spans,
      scope      TYPE zif_otel_otlp_common=>instrumentation_scope,
      spans      TYPE STANDARD TABLE OF span WITH EMPTY KEY,
      schema_url TYPE string,
    END OF scope_spans,

    "! Collection of spans from a resource
    BEGIN OF resource_spans,
      resource    TYPE zif_otel_otlp_resource=>resource,
      scope_spans TYPE STANDARD TABLE OF scope_spans WITH EMPTY KEY,
      schema_url  TYPE string,
    END OF resource_spans,

    "! Trace data
    BEGIN OF traces_data,
      resource_spans TYPE STANDARD TABLE OF resource_spans WITH EMPTY KEY,
    END OF traces_data.

ENDINTERFACE.
