"! <p class="shorttext">OTLP Trace Interface</p>
"! Generated by AI - do not maintain manually
INTERFACE zif_otel_otlp_trace PUBLIC.

  TYPES:
    "! Status code enum type
    status_code_type TYPE i,

    "! Status code enum values
    BEGIN OF status_code,
      unset TYPE status_code_type VALUE 0,
      ok    TYPE status_code_type VALUE 1,
      error TYPE status_code_type VALUE 2,
    END OF status_code,

    "! Span kind enum type  
    span_kind_type TYPE i,

    "! Span kind enum values
    BEGIN OF span_kind,
      unspecified TYPE span_kind_type VALUE 0,
      internal    TYPE span_kind_type VALUE 1,
      server      TYPE span_kind_type VALUE 2,
      client      TYPE span_kind_type VALUE 3,
      producer    TYPE span_kind_type VALUE 4,
      consumer    TYPE span_kind_type VALUE 5,
    END OF span_kind,

    "! Status message
    BEGIN OF status,
      message TYPE string,
      code    TYPE status_code_type,
    END OF status,

    "! Link attributes
    BEGIN OF link,
      trace_id                 TYPE string,
      span_id                 TYPE string,
      trace_state            TYPE string,
      attributes             TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
      flags                  TYPE i,
    END OF link,

    "! Event attributes
    BEGIN OF event,
      time_unix_nano         TYPE string,
      name                  TYPE string,
      attributes            TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
    END OF event,

    "! Span definition
    BEGIN OF span,
      trace_id                TYPE string,
      span_id                TYPE string,
      trace_state           TYPE string,
      parent_span_id        TYPE string,
      flags                 TYPE i,
      name                  TYPE string,
      kind                  TYPE span_kind_type,
      start_time_unix_nano  TYPE string,
      end_time_unix_nano    TYPE string,
      attributes            TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      dropped_attributes_count TYPE i,
      events                TYPE STANDARD TABLE OF event WITH EMPTY KEY,
      dropped_events_count   TYPE i,
      links                 TYPE STANDARD TABLE OF link WITH EMPTY KEY,
      dropped_links_count    TYPE i,
      status                TYPE status,
    END OF span,

    "! Scope spans
    BEGIN OF scope_spans,
      scope       TYPE zif_otel_otlp_common=>instrumentation_scope,
      spans       TYPE STANDARD TABLE OF span WITH EMPTY KEY,
      schema_url  TYPE string,
    END OF scope_spans,

    "! Resource spans
    BEGIN OF resource_spans,
      resource    TYPE zif_otel_otlp_resource=>resource,
      scope_spans TYPE STANDARD TABLE OF scope_spans WITH EMPTY KEY,
      schema_url  TYPE string,
    END OF resource_spans,

    "! Traces data
    BEGIN OF traces_data,
      resource_spans TYPE STANDARD TABLE OF resource_spans WITH EMPTY KEY,
    END OF traces_data.

ENDINTERFACE.
