"! <p class="shorttext">OTLP Metrics Interface</p>
"! Generated by AI - do not maintain manually
INTERFACE zif_otel_otlp_metrics PUBLIC.

  TYPES:
    "! Aggregation temporality type
    aggregation_temporality_type TYPE i,

    "! Data point flags type  
    data_point_flags_type TYPE i.

  CONSTANTS:
    BEGIN OF aggregation_temporality,
      unspecified TYPE aggregation_temporality_type VALUE 0,
      delta       TYPE aggregation_temporality_type VALUE 1,
      cumulative  TYPE aggregation_temporality_type VALUE 2,
    END OF aggregation_temporality,

    BEGIN OF data_point_flags,
      do_not_use           TYPE data_point_flags_type VALUE 0,
      no_recorded_value    TYPE data_point_flags_type VALUE 1,
    END OF data_point_flags.

  TYPES:
    "! Value at quantile
    BEGIN OF value_at_quantile,
      quantile TYPE f,
      value    TYPE f,
    END OF value_at_quantile,

    "! Table of value at quantile
    value_at_quantile_list TYPE STANDARD TABLE OF value_at_quantile WITH EMPTY KEY,

    "! Exemplar
    BEGIN OF exemplar,
      filtered_attributes TYPE zif_otel_otlp_common=>key_value_list,
      time_unix_nano     TYPE int8,
      as_double         TYPE f,
      as_int           TYPE int8,
      span_id          TYPE string,
      trace_id         TYPE string,
    END OF exemplar,

    "! Table of exemplars
    exemplar_list TYPE STANDARD TABLE OF exemplar WITH EMPTY KEY,

    "! Buckets
    BEGIN OF buckets,
      offset        TYPE i,
      bucket_counts TYPE STANDARD TABLE OF int8 WITH EMPTY KEY,
    END OF buckets,

    "! Summary data point
    BEGIN OF summary_data_point,
      attributes           TYPE zif_otel_otlp_common=>key_value_list,
      start_time_unix_nano TYPE int8,
      time_unix_nano       TYPE int8,
      count               TYPE int8,
      sum                 TYPE f,
      quantile_values     TYPE value_at_quantile_list,
      flags               TYPE i,
    END OF summary_data_point,

    "! Table of summary data points
    summary_data_point_list TYPE STANDARD TABLE OF summary_data_point WITH EMPTY KEY,

    "! Exponential histogram data point
    BEGIN OF exponential_histogram_data_point,
      attributes           TYPE zif_otel_otlp_common=>key_value_list,
      start_time_unix_nano TYPE int8,
      time_unix_nano       TYPE int8,
      count               TYPE int8,
      sum                 TYPE f,
      scale              TYPE i,
      zero_count         TYPE int8,
      positive           TYPE buckets,
      negative           TYPE buckets,
      flags              TYPE i,
      exemplars          TYPE exemplar_list,
      min                TYPE f,
      max                TYPE f,
      zero_threshold     TYPE f,
    END OF exponential_histogram_data_point,

    "! Table of exponential histogram data points
    exponential_histogram_data_point_list TYPE STANDARD TABLE OF exponential_histogram_data_point WITH EMPTY KEY,

    "! Histogram data point
    BEGIN OF histogram_data_point,
      attributes           TYPE zif_otel_otlp_common=>key_value_list,
      start_time_unix_nano TYPE int8,
      time_unix_nano       TYPE int8,
      count               TYPE int8,
      sum                 TYPE f,
      bucket_counts       TYPE STANDARD TABLE OF int8 WITH EMPTY KEY,
      explicit_bounds     TYPE STANDARD TABLE OF f WITH EMPTY KEY,
      exemplars           TYPE exemplar_list,
      flags               TYPE i,
      min                 TYPE f,
      max                 TYPE f,
    END OF histogram_data_point,

    "! Table of histogram data points
    histogram_data_point_list TYPE STANDARD TABLE OF histogram_data_point WITH EMPTY KEY,

    "! Number data point
    BEGIN OF number_data_point,
      attributes           TYPE zif_otel_otlp_common=>key_value_list,
      start_time_unix_nano TYPE int8,
      time_unix_nano       TYPE int8,
      as_double           TYPE f,
      as_int              TYPE int8,
      exemplars           TYPE exemplar_list,
      flags               TYPE i,
    END OF number_data_point,

    "! Table of number data points
    number_data_point_list TYPE STANDARD TABLE OF number_data_point WITH EMPTY KEY,

    "! Summary metric
    BEGIN OF summary,
      data_points TYPE summary_data_point_list,
    END OF summary,

    "! Exponential histogram metric
    BEGIN OF exponential_histogram,
      data_points             TYPE exponential_histogram_data_point_list,
      aggregation_temporality TYPE i,
    END OF exponential_histogram,

    "! Histogram metric
    BEGIN OF histogram,
      data_points             TYPE histogram_data_point_list,
      aggregation_temporality TYPE i,
    END OF histogram,

    "! Sum metric
    BEGIN OF sum,
      data_points             TYPE number_data_point_list,
      aggregation_temporality TYPE i,
      is_monotonic           TYPE xsdboolean,
    END OF sum,

    "! Gauge metric
    BEGIN OF gauge,
      data_points TYPE number_data_point_list,
    END OF gauge,

    "! Metric
    BEGIN OF metric,
      name        TYPE string,
      description TYPE string,
      unit        TYPE string,
      gauge       TYPE gauge,
      sum         TYPE sum,
      histogram   TYPE histogram,
      exponential_histogram TYPE exponential_histogram,
      summary     TYPE summary,
      metadata    TYPE zif_otel_otlp_common=>key_value_list,
    END OF metric,

    "! Table of metrics
    metric_list TYPE STANDARD TABLE OF metric WITH EMPTY KEY,

    "! Scope metrics
    BEGIN OF scope_metrics,
      scope       TYPE zif_otel_otlp_common=>instrumentation_scope,
      metrics     TYPE metric_list,
      schema_url  TYPE string,
    END OF scope_metrics,

    "! Table of scope metrics
    scope_metrics_list TYPE STANDARD TABLE OF scope_metrics WITH EMPTY KEY,

    "! Resource metrics
    BEGIN OF resource_metrics,
      resource     TYPE zif_otel_otlp_resource=>resource,
      scope_metrics TYPE scope_metrics_list,
      schema_url   TYPE string,
    END OF resource_metrics,

    "! Table of resource metrics
    resource_metrics_list TYPE STANDARD TABLE OF resource_metrics WITH EMPTY KEY,

    "! Metrics data
    BEGIN OF metrics_data,
      resource_metrics TYPE resource_metrics_list,
    END OF metrics_data.

ENDINTERFACE.
