INTERFACE zif_otel_otlp_metrics PUBLIC.
* Generated by AI - do not maintain manually
* Based on opentelemetry/proto/metrics/v1/metrics.proto

  TYPES:
    "! AggregationTemporality enum type
    aggregation_temporality_type TYPE i,

    "! DataPointFlags enum type
    data_point_flags_type TYPE i.

  CONSTANTS:
    BEGIN OF aggregation_temporality,
      unspecified TYPE aggregation_temporality_type VALUE 0,
      delta       TYPE aggregation_temporality_type VALUE 1,
      cumulative  TYPE aggregation_temporality_type VALUE 2,
    END OF aggregation_temporality,

    BEGIN OF data_point_flags,
      do_not_use           TYPE data_point_flags_type VALUE 0,
      no_recorded_value    TYPE data_point_flags_type VALUE 1,
    END OF data_point_flags.

  TYPES:
    "! Single exemplar value
    BEGIN OF exemplar,
      filtered_attributes TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      time_unix_nano     TYPE string,
      as_double         TYPE f,
      as_int           TYPE string,
      span_id          TYPE string,
      trace_id         TYPE string,
    END OF exemplar,

    "! Table of exemplars
    exemplars TYPE STANDARD TABLE OF exemplar WITH EMPTY KEY,

    "! Single number data point
    BEGIN OF number_data_point,
      attributes           TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      start_time_unix_nano TYPE string,
      time_unix_nano      TYPE string,
      as_double          TYPE f,
      as_int            TYPE string,
      exemplars         TYPE exemplars,
      flags             TYPE i,
    END OF number_data_point,

    "! Table of number data points
    number_data_points TYPE STANDARD TABLE OF number_data_point WITH EMPTY KEY,

    "! Single gauge metric
    BEGIN OF gauge,
      data_points TYPE number_data_points,
    END OF gauge,

    "! Single sum metric
    BEGIN OF sum,
      data_points             TYPE number_data_points,
      aggregation_temporality TYPE i,
      is_monotonic           TYPE xsdboolean,
    END OF sum,

    "! Single histogram data point
    BEGIN OF histogram_data_point,
      attributes           TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      start_time_unix_nano TYPE string,
      time_unix_nano      TYPE string,
      count              TYPE string,
      sum                TYPE f,
      bucket_counts      TYPE STANDARD TABLE OF string WITH EMPTY KEY,
      explicit_bounds    TYPE STANDARD TABLE OF f WITH EMPTY KEY,
      exemplars         TYPE exemplars,
      flags             TYPE i,
      min               TYPE f,
      max               TYPE f,
    END OF histogram_data_point,

    "! Table of histogram data points
    histogram_data_points TYPE STANDARD TABLE OF histogram_data_point WITH EMPTY KEY,

    "! Single histogram metric
    BEGIN OF histogram,
      data_points             TYPE histogram_data_points,
      aggregation_temporality TYPE i,
    END OF histogram,

    "! Exponential histogram buckets
    BEGIN OF exp_hist_buckets,
      offset        TYPE i,
      bucket_counts TYPE STANDARD TABLE OF string WITH EMPTY KEY,
    END OF exp_hist_buckets,

    "! Single exponential histogram data point
    BEGIN OF exp_histogram_data_point,
      attributes           TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      start_time_unix_nano TYPE string,
      time_unix_nano      TYPE string,
      count              TYPE string,
      sum                TYPE f,
      scale             TYPE i,
      zero_count        TYPE string,
      positive          TYPE exp_hist_buckets,
      negative          TYPE exp_hist_buckets,
      flags             TYPE i,
      exemplars         TYPE exemplars,
      min               TYPE f,
      max               TYPE f,
      zero_threshold    TYPE f,
    END OF exp_histogram_data_point,

    "! Table of exponential histogram data points
    exp_histogram_data_points TYPE STANDARD TABLE OF exp_histogram_data_point WITH EMPTY KEY,

    "! Single exponential histogram metric
    BEGIN OF exp_histogram,
      data_points             TYPE exp_histogram_data_points,
      aggregation_temporality TYPE i,
    END OF exp_histogram,

    "! Single summary value at quantile
    BEGIN OF value_at_quantile,
      quantile TYPE f,
      value    TYPE f,
    END OF value_at_quantile,

    "! Table of values at quantiles
    values_at_quantiles TYPE STANDARD TABLE OF value_at_quantile WITH EMPTY KEY,

    "! Single summary data point
    BEGIN OF summary_data_point,
      attributes           TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
      start_time_unix_nano TYPE string,
      time_unix_nano      TYPE string,
      count              TYPE string,
      sum                TYPE f,
      quantile_values    TYPE values_at_quantiles,
      flags              TYPE i,
    END OF summary_data_point,

    "! Table of summary data points
    summary_data_points TYPE STANDARD TABLE OF summary_data_point WITH EMPTY KEY,

    "! Single summary metric
    BEGIN OF summary,
      data_points TYPE summary_data_points,
    END OF summary,

    "! Single metric
    BEGIN OF metric,
      name        TYPE string,
      description TYPE string,
      unit        TYPE string,
      gauge       TYPE gauge,
      sum         TYPE sum,
      histogram   TYPE histogram,
      exp_histogram TYPE exp_histogram,
      summary     TYPE summary,
      metadata    TYPE STANDARD TABLE OF zif_otel_otlp_common=>key_value WITH EMPTY KEY,
    END OF metric,

    "! Table of metrics
    metrics TYPE STANDARD TABLE OF metric WITH EMPTY KEY,

    "! Single scope metrics
    BEGIN OF scope_metrics,
      scope       TYPE zif_otel_otlp_common=>instrumentation_scope,
      metrics     TYPE metrics,
      schema_url  TYPE string,
    END OF scope_metrics,

    "! Table of scope metrics
    scope_metrics_list TYPE STANDARD TABLE OF scope_metrics WITH EMPTY KEY,

    "! Single resource metrics
    BEGIN OF resource_metrics,
      resource     TYPE zif_otel_otlp_resource=>resource,
      scope_metrics TYPE scope_metrics_list,
      schema_url   TYPE string,
    END OF resource_metrics,

    "! Table of resource metrics
    resource_metrics_list TYPE STANDARD TABLE OF resource_metrics WITH EMPTY KEY,

    "! Top level metrics data
    BEGIN OF metrics_data,
      resource_metrics TYPE resource_metrics_list,
    END OF metrics_data.

ENDINTERFACE.
